const APPLICANTS = [
  {
    name: "Prasad Khake", rank: 1, tier: "S", tierLabel: "Auto-Accept",
    city: "Pune", age: "~28-30", track: "STAGE 1", applyType: "solo", canCommit: "yes_all",
    vertical: "Hardware / IoT / SaaS / pSEO",
    building: "penna.ink (LinkedIn SaaS) + E-paper air particulate monitor",
    headline: "AI GTM Engineer",
    linkedin: "linkedin.com/in/prasadkhake", liFollowers: 5665, liConnections: 5673,
    github: "robertlangdonn", ghRepos: 6, ghOriginal: 5, ghStars: 4, ghLanguages: "JS, HTML, TS",
    education: "MIT Pune — BE",
    experience: "AI GTM Engineer (confidential) + CEO paperd.ink (2020-present) + Marketing Manager (2022-2024)",
    expYears: 6,
    founderSignals: [
      "paperd.ink — #1 on Hacker News + Reddit viral",
      "Grant from Zerodha CTO (Kailash Nadh) + FOSSUnited",
      "Shipped hardware to 20+ countries, managed China production",
      "12+ projects on portfolio (7 redacted = NDA client work)",
      "600+ programmatic SEO pages generating referral revenue",
      "Medical content pipeline: 500K+ words, 250+ articles",
      "penna.ink SaaS earning revenue"
    ],
    website: "prasadkhake.com", hasVideo: false,
    videoSummary: null,
    mentorMatch: "Hardware/IoT, SaaS GTM, pSEO, Content",
    risk: "Splitting focus — but track record shows he finishes what he starts",
    scores: { founderCredibility: 10, techDepth: 8, industryFit: 9, commitment: 10, epochReadiness: 9 },
    totalScore: 46,
    phone: "+918975772486", email: "prasadkhake@gmail.com"
  },
  {
    name: "Prasad Hajare", rank: 2, tier: "S", tierLabel: "Auto-Accept",
    city: "Nagpur", age: "~28-32", track: "STAGE 1", applyType: "solo", canCommit: "yes_all",
    vertical: "AI SaaS / MarTech / SMB Tools",
    building: "Avianya AI — unified marketing platform (WhatsApp, Meta Ads, RCS, SMS, AI bots, CRM)",
    headline: "Building Avianya | Automating Conversations through WhatsApp, RCS & SMS",
    linkedin: "linkedin.com/in/prasad-hajare", liFollowers: 3440, liConnections: 3319,
    github: null, ghRepos: 0, ghOriginal: 0, ghStars: 0, ghLanguages: "",
    education: "Great Lakes — PG in Data Science & Engineering",
    experience: "Founder Avianya (2025-present) + Data Scientist intern + Back End Dev + Dev Consultant",
    expYears: 3,
    founderSignals: [
      "3 paying clients in production",
      "180+ API endpoints, solo-built",
      "Avianya AI Pvt Ltd registered company (MCA, Mar 2026)",
      "DPIIT recognized startup",
      "WhatsApp Cloud API, Meta Ads API, WebRTC, AI creative gen",
      "Multi-tenant auth, 50K+ messages campaign engine",
      "3,440 LinkedIn followers"
    ],
    website: "avianya.com", hasVideo: true,
    videoSummary: "Confident pitch. Confirms 3 paid clients, DPIIT recognized. 'I've built most of the ecosystem as a solo founder.'",
    mentorMatch: "SaaS GTM, SMB distribution, India market",
    risk: "Nagpur-based (travel to Pune). Solo = single point of failure.",
    scores: { founderCredibility: 10, techDepth: 9, industryFit: 10, commitment: 9, epochReadiness: 10 },
    totalScore: 48,
    phone: "+917755991051", email: "prasad@avianya.com"
  },
  {
    name: "Pritam Pawar", rank: 3, tier: "S", tierLabel: "Auto-Accept",
    city: "Ahmednagar", age: "~23-25", track: "STAGE 0", applyType: "solo", canCommit: "yes_all",
    vertical: "AI Video Editing / Creator Tools",
    building: "Alkemii Labs — AI video editor, style transfer from reference videos",
    headline: "Making video editing as easy as texting | Co-Founded TournaHub | Ex-Sprinklr | NIT Allahabad",
    linkedin: "linkedin.com/in/pritam-pawar-070788197", liFollowers: 1459, liConnections: 1471,
    github: "pritamp17", ghRepos: 238, ghOriginal: 52, ghStars: 5, ghLanguages: "JS(21), Python(8), Java(7)",
    education: "NIT Allahabad — BTech (Motilal Nehru NIT)",
    experience: "Co-Founder Alkemii (2026) + TournaHub (2025) + Sprinklr SDE (2023-2025) + TartanHQ (2023)",
    expYears: 5,
    founderSignals: [
      "NIT Allahabad (top engineering college)",
      "Ex-Sprinklr (2yr at $4B unicorn) — Kafka, Selenium Grid, Spring Boot",
      "Co-Founded TournaHub — 1000+ users on both app stores, 400+ gamers",
      "Alkemii Labs — 50 beta users, live at alkemiilabs.com",
      "238 GitHub repos (52 original, 186 forked) — obsessive builder",
      "17 repos active in last 90 days",
      "Shipped Alkemii in 7 weeks with 2 interns"
    ],
    website: "pritampawar.com + alkemiilabs.com", hasVideo: true,
    videoSummary: "Polished pitch. 'World's best AI agentic video editor.' Mentions 50 beta users. Confident delivery.",
    mentorMatch: "Creator economy, video/media tech, consumer growth",
    risk: "Ahmednagar-based. But left Sprinklr in Gurgaon — willing to relocate.",
    scores: { founderCredibility: 9, techDepth: 9, industryFit: 9, commitment: 10, epochReadiness: 9 },
    totalScore: 46,
    phone: "+919577558080", email: "pritampawar625@gmail.com"
  },
  {
    name: "Ajinkya Takawale + Kaustubh", rank: 4, tier: "S", tierLabel: "Auto-Accept",
    city: "Pune", age: "~30-32", track: "STAGE 1", applyType: "team", canCommit: "yes_all",
    vertical: "AI Video Production / GenAI / Media",
    building: "Mixio — agentic AI for scripts → commercial-grade videos",
    headline: "Founder & AI Head @ Mixio | AI Media Generation | IIT Kharagpur",
    linkedin: "linkedin.com/in/ajinkyat", liFollowers: 3432, liConnections: 3423,
    github: "ajinkyaT", ghRepos: 94, ghOriginal: 36, ghStars: 204, ghLanguages: "Jupyter(32), Python(25), HTML(5), R(5)",
    education: "IIT Kharagpur — BTech Mechanical (both founders IIT KGP!)",
    experience: "CEO Mixio (2025) + CTO Mixio (2024-25) + ML Engineer Legal Tech (2022-24) + Assoc Data Scientist HubSpot/CV (2021-22) + AI/ML Engineer (2019-21) + 3 internships",
    expYears: 8,
    founderSignals: [
      "IIT Kharagpur (both Ajinkya AND Harshit Chouhan from same college)",
      "200+ GitHub stars — CNN_Intent_Classification(★101), Lip_Reading(★61), FAQ_Chatbot(★34)",
      "8+ years AI career, worked in Japan",
      "Published models on HuggingFace pre-ChatGPT",
      "CTO Kaustubh = Founding Engineer at Vapi (YC-backed)",
      "Team of 5+ with Creative lead",
      "3,432 LinkedIn followers",
      "India AI Impact Summit 2026 speaker"
    ],
    website: "mixio.studio", hasVideo: false,
    videoSummary: null,
    mentorMatch: "AI/ML deep tech, media/entertainment, enterprise B2B video",
    risk: "May be overqualified — already well-resourced. Could be cohort anchor.",
    scores: { founderCredibility: 10, techDepth: 10, industryFit: 9, commitment: 10, epochReadiness: 8 },
    totalScore: 47,
    phone: "8768007772", email: "admin@mixio.studio"
  },
  {
    name: "Ismail Patel", rank: 5, tier: "S", tierLabel: "Auto-Accept",
    city: "Pune", age: "~26-30", track: "STAGE 0", applyType: "solo", canCommit: "yes_all",
    vertical: "AI Marketing / SEO / MSME Tools",
    building: "AI inbound engine for MSMEs — vernacular landing pages, SEO, backlinking",
    headline: "Building India's Largest MSME AI Transformation Initiative",
    linkedin: "linkedin.com/in/ismail-patel-8a475518b", liFollowers: 1890, liConnections: 1901,
    github: null, ghRepos: 0, ghOriginal: 0, ghStars: 0, ghLanguages: "",
    education: "Vishwakarma University — BTech",
    experience: "MCCIA Applied AI Studio (present) + Process Optimization Intern + SW Dev Intern Urban95 + Product Dev Intern + Event Director",
    expYears: 4,
    founderSignals: [
      "Co-built MCCIA Applied AI Studio from 0 to 1",
      "550+ MSMEs benefited across Maharashtra",
      "700+ consulting sessions, ~25% efficiency gains",
      "Managing 5-member team",
      "Automations saving ₹3L/year per business",
      "Full Stack Developer + Applied AI Engineer",
      "1,890 LinkedIn followers"
    ],
    website: null, hasVideo: false,
    videoSummary: null,
    mentorMatch: "B2B sales, India MSME market, growth marketing, vernacular tech",
    risk: "Product is Stage 0 — but 700+ customer conversations means he knows what to build",
    scores: { founderCredibility: 9, techDepth: 7, industryFit: 10, commitment: 10, epochReadiness: 8 },
    totalScore: 44,
    phone: "8788737771", email: "ismailpatel3290@gmail.com"
  },
  {
    name: "Pritesh Kamdi", rank: 6, tier: "S", tierLabel: "Auto-Accept",
    city: "Pune", age: "~25-28", track: "STAGE 0", applyType: "solo", canCommit: "yes_all",
    vertical: "B2B Data / Lead Gen / Sales Tech",
    building: "Zero-touch DaaS engine — extract new businesses via Google Maps bypass, enrich, cold outbound",
    headline: "A geek, interested in computing, AI & Linux.",
    linkedin: "linkedin.com/in/prtsh", liFollowers: 319, liConnections: 322,
    github: "theprtsh", ghRepos: 16, ghOriginal: 15, ghStars: 2, ghLanguages: "Python(7), HTML(2), Kotlin(1), JS(1)",
    education: "Savitribai Phule Pune University — BTech",
    experience: "HungryHub V1 builder (earned ₹2L) + freelance",
    expYears: 3,
    founderSignals: [
      "Built V1 for HungryHub (Zomato competitor, Bangkok) — earned ₹2L",
      "Reverse-engineered Google's hidden Protobuf arrays",
      "V2: fault-tolerant TS/Bun/Crawlee/BullMQ stack",
      "Kaggle profile (data science)",
      "Active on Mastodon, Bluesky, Telegram",
      "Specific Epoch goal: 'close 10 paying B2B subs'"
    ],
    website: "prtsh.com", hasVideo: true,
    videoSummary: "Very short (~25 sec). States what he's building, says thanks. Missed opportunity.",
    mentorMatch: "B2B sales, data infra, growth hacking, outbound automation",
    risk: "Small public footprint but the work speaks for itself",
    scores: { founderCredibility: 8, techDepth: 9, industryFit: 9, commitment: 10, epochReadiness: 9 },
    totalScore: 45,
    phone: "+918390569583", email: "theprtsh@gmail.com"
  },
  {
    name: "Niraj Puran Rao", rank: 7, tier: "S", tierLabel: "Auto-Accept",
    city: "Pune", age: "~28-32", track: "STAGE 0", applyType: "solo", canCommit: "yes_all",
    vertical: "AI Agents / Marketing / Sports Tech",
    building: "GDPR AI marketing + adaptive trading + BNI for AI agents",
    headline: "Gen AI | Agentic AI Engineer | Adobe Journey Optimizer Expert | MarTech",
    linkedin: "linkedin.com/in/niraj-rao", liFollowers: 2540, liConnections: 1795,
    github: null, ghRepos: 0, ghOriginal: 0, ghStars: 0, ghLanguages: "",
    education: "IIT Roorkee — PG in Gen AI/Agentic + Symbiosis — MBA Sports Mgmt",
    experience: "MarTech Lead (2025-present) + Executive Producer (2022-25) + Partnerships (2022) + Content/Production (2019-22) + Sales (2018-19) + TidySpidey founder (2015-16) + Pro footballer (2013-15)",
    expYears: 12,
    founderSignals: [
      "The Apprentice: ONE Championship Edition — sole India representative",
      "IIT Roorkee PG in Gen AI/Agentic (in addition to Symbiosis MBA)",
      "Marketing Automation Lead — Adobe AJO Expert",
      "Executive Producer for 3 years",
      "Pro soccer player + Shotokan black belt + bodybuilder",
      "Built npr-fights.netlify.app — full fight prep OS",
      "2,540 LinkedIn followers",
      "Featured: The Hindu, Business Standard, ONE FC, Essentially Sports"
    ],
    website: "npr-fights.netlify.app", hasVideo: true,
    videoSummary: "Authentic, high energy. 'I come from places you wouldn't expect — professional sports, media across Asia.' Finishing AI course from IIT Roorkee.",
    mentorMatch: "Sports tech, consumer AI, media/PR, GTM",
    risk: "3 parallel builds = scatter. Needs to pick one.",
    scores: { founderCredibility: 9, techDepth: 6, industryFit: 8, commitment: 10, epochReadiness: 7 },
    totalScore: 40,
    phone: "9545056018", email: "nirajpuranrao1@gmail.com"
  },
  {
    name: "Varun Gupta", rank: 8, tier: "S", tierLabel: "Auto-Accept",
    city: "Gurgaon → Bengaluru", age: "~17-19", track: "STAGE 0", applyType: "solo", canCommit: "yes_all",
    vertical: "AI Audio / Dubbing / Media Tech",
    building: "AI movie dubbing — bicodec tokenizer, any language cheaply",
    headline: "Building HelpingAI || Antler AIR 7 (youngest to get selected)",
    linkedin: "linkedin.com/in/varun-gupta-42b120263", liFollowers: 3392, liConnections: 2832,
    github: null, ghRepos: 0, ghOriginal: 0, ghStars: 0, ghLanguages: "",
    education: "Not listed on LinkedIn (likely still in school/early college)",
    experience: "Co-Founder CTO HelpingAI (2024-present) + Co-Founder (2023-24) + Founder (2022-23)",
    expYears: 4,
    founderSignals: [
      "Youngest ever accepted to Antler AIR 7 (Antler AI Residency)",
      "Co-Founder & CTO HelpingAI — 1.5M+ OS downloads",
      "World's first intermediate reasoning model (5-10x more efficient than DeepSeek-r1)",
      "HuggingFace: HelpingAI-3B-v2, HelpingAI2-9B, Dhanishtha 2.0",
      "Featured: TechQuity India, Reddit, StackForce, Foundry events",
      "3,392 LinkedIn followers at age ~18",
      "Competing in YC Vibecon Round 2"
    ],
    website: null, hasVideo: false,
    videoSummary: null,
    mentorMatch: "AI/ML research, media tech, open source → commercial monetization",
    risk: "Very young, Gurgaon/Bengaluru (travel to Pune), researcher > business?",
    scores: { founderCredibility: 9, techDepth: 10, industryFit: 8, commitment: 8, epochReadiness: 7 },
    totalScore: 42,
    phone: "+91 93154 55291", email: "varun.gupta.py@gmail.com"
  },
  {
    name: "Basil Paulose", rank: 9, tier: "S", tierLabel: "Auto-Accept",
    city: "Mumbai", age: "~25-28", track: "STAGE 1", applyType: "solo", canCommit: "yes_all",
    vertical: "Climate Tech / Carbon Markets / FinTech",
    building: "Reoxide AI — India's 1st AI-powered carbon credit marketplace",
    headline: "Building Reoxide AI India's 1st AI Powered Carbon Trading Marketplace",
    linkedin: "linkedin.com/in/basil-paulose-617b64261", liFollowers: 2628, liConnections: 2613,
    github: null, ghRepos: 0, ghOriginal: 0, ghStars: 0, ghLanguages: "",
    education: "University of Edinburgh — Master's degree",
    experience: "Founder Reoxide (2025-present) + EIR ×4 (Draper, Climate Collective, etc.) + Founder Office + Claims Analyst + Intern",
    expYears: 3,
    founderSignals: [
      "University of Edinburgh — Master's",
      "Draper Startup House Founders Program Cohort 1",
      "4 different EIR programs back-to-back (2025)",
      "UCR partnership (Universal Carbon Registry)",
      "10M+ carbon credits onboarded",
      "AI ESG Analyzer + blockchain smart contracts",
      "Press: OpenPR, Medium (UCR official)",
      "YC Startup School waitlist",
      "2,628 LinkedIn followers"
    ],
    website: "reoxide.com", hasVideo: false,
    videoSummary: null,
    mentorMatch: "Climate tech, FinTech, marketplace, institutional sales, fundraising",
    risk: "Mumbai-based. Carbon markets = long sales cycles.",
    scores: { founderCredibility: 9, techDepth: 8, industryFit: 9, commitment: 10, epochReadiness: 8 },
    totalScore: 44,
    phone: "+91 98332 39950", email: "basil@reoxide.com"
  },
  {
    name: "Mayur Patil", rank: 10, tier: "S", tierLabel: "Auto-Accept",
    city: "Pune", age: "~21-23", track: "STAGE 1", applyType: "solo", canCommit: "yes_all",
    vertical: "HealthTech / Ayurveda / Clinic SaaS",
    building: "Ayurvedic Clinic Management SaaS — 500K+ target practitioners",
    headline: "ML Undergrad | 2026",
    linkedin: "linkedin.com/in/mayur5204", liFollowers: 222, liConnections: 220,
    github: "mayur5204", ghRepos: 6, ghOriginal: 6, ghStars: 6, ghLanguages: "TypeScript(3), JS(1), CSS(1)",
    education: "PES Modern College — BE in AI & ML",
    experience: "Student + builder",
    expYears: 1,
    founderSignals: [
      "Live Clinic Management SaaS (Clinic-Mangement-New on GitHub)",
      "Dairy Billing App — in production with real client",
      "Offline-first architecture (rural India connectivity)",
      "Multi-language, SMS notifications, PDF receipts",
      "4 repos active in last 90 days",
      "Target: 500K unorganized Ayurvedic practitioners"
    ],
    website: null, hasVideo: false,
    videoSummary: null,
    mentorMatch: "HealthTech, India rural/SMB, SaaS pricing",
    risk: "Young, small GitHub presence, solo",
    scores: { founderCredibility: 7, techDepth: 7, industryFit: 9, commitment: 10, epochReadiness: 8 },
    totalScore: 41,
    phone: "+917397887032", email: "mayurpatil5204@outlook.com"
  },
  {
    name: "Raghvendra Dharmapurikar", rank: 11, tier: "A", tierLabel: "Interview",
    city: "Pune", age: "~40+", track: "STAGE 0", applyType: "solo", canCommit: "yes_all",
    vertical: "EdTech / HealthTech / SMB Back-Office",
    building: "(1) AI student report card (2) AI back-office for small businesses",
    headline: "Head of Engineering | Building Scalable Healthcare Products | Stanford LEAD | AWS Solution Architect",
    linkedin: "linkedin.com/in/raghvendra-dharmapurikar", liFollowers: 551, liConnections: 533,
    github: null, ghRepos: 0, ghOriginal: 0, ghStars: 0, ghLanguages: "",
    education: "Stanford GSB — Executive Education + Other engineering",
    experience: "Head of Eng @ Higgs Boson Health (2022-present) + Lead Consultant (2020-22) + Lead App Dev (2015-20, 5yr!) + Senior SE ×2 (2012-15)",
    expYears: 13,
    founderSignals: [
      "Stanford LEAD graduate",
      "Head of Engineering at Higgs Boson Health",
      "AWS Solution Architect certified",
      "13 years engineering career",
      "Built MyFuture app for Medtronic (App Store)",
      "MASSIVELY underreported on application"
    ],
    website: null, hasVideo: true,
    videoSummary: "Confirms Head of Eng at Higgs Boson Health. Two ideas well-explained. Professional, notably modest despite massive experience.",
    mentorMatch: "Enterprise software, HealthTech, EdTech, product leadership",
    risk: "Two ideas (needs to pick one). Used to larger teams/timelines.",
    scores: { founderCredibility: 9, techDepth: 8, industryFit: 8, commitment: 9, epochReadiness: 7 },
    totalScore: 41,
    phone: "9922445126", email: "raghvendra.d@gmail.com"
  },
  {
    name: "Shashi Kant", rank: 12, tier: "A", tierLabel: "Interview",
    city: "Jamshedpur/Mumbai", age: "~28-30", track: "STAGE 0", applyType: "solo", canCommit: "yes_all",
    vertical: "Distributed Systems / Cloud / Infrastructure",
    building: "Distributed personal computing — lightweight devices, scale specs on demand",
    headline: "SDE1 (Frontend) @Jupiter | NIT Jamshedpur",
    linkedin: "linkedin.com/in/shashi-kant-02589421a", liFollowers: 449, liConnections: 450,
    github: "shashitnak", ghRepos: 51, ghOriginal: 30, ghStars: 2, ghLanguages: "Rust(24), Python(3), Julia(3), Haskell(2), JS(2)",
    education: "NIT Jamshedpur — BTech (+ PhD IIT Bombay per getprog.ai)",
    experience: "SDE1 Jupiter (2025-present) + Frontend Dev (2023-25) + ex-Juspay (ISO8583) + ex-Tailcall (Rust) + ex-Turing (Haskell) + ex-TCS",
    expYears: 6,
    founderSignals: [
      "PhD Student at IIT Bombay (per getprog.ai)",
      "Ex-Juspay — built ISO8583 parser from scratch (replaced proprietary software)",
      "Rust developer at Tailcall (238 pushes to gh-action)",
      "Haskell developer at Turing",
      "Rated 'Rockstar' + 'Top School' by Prog.ai",
      "62 GitHub skills tracked",
      "24 Rust repos — deep systems programming",
      "Built: NEAT algorithm in Rust, neural network from scratch in Julia, dVPN"
    ],
    website: null, hasVideo: false,
    videoSummary: null,
    mentorMatch: "Deep tech, distributed systems, cloud, developer tools",
    risk: "PhD competing time. Jamshedpur/Mumbai — Pune travel. Ambitious idea for 4 weekends.",
    scores: { founderCredibility: 7, techDepth: 10, industryFit: 7, commitment: 9, epochReadiness: 6 },
    totalScore: 39,
    phone: "+91 99550-59230", email: "shashikant42@proton.me"
  },
  {
    name: "Colrows Team (3)", rank: 13, tier: "A", tierLabel: "Interview",
    city: "Pune (all 3)", age: "35-40+", track: "STAGE 0-1", applyType: "team", canCommit: "yes_all",
    vertical: "AI Data Infrastructure / Enterprise Analytics",
    building: "Colrows — autonomous AI semantic layer for enterprise data",
    headline: "Yogendra: Building Colrows | Autonomous Semantic Reasoning Infrastructure",
    linkedin: "linkedin.com/in/syogendra", liFollowers: 9285, liConnections: 9206,
    github: null, ghRepos: 0, ghOriginal: 0, ghStars: 0, ghLanguages: "",
    education: "Harshit: IIT Kharagpur — Integrated MSc | Yogendra: JNVU — BE | Nilesh: GHRCE Nagpur — BE",
    experience: "Yogendra: 20yr (Global Head Data Distribution, AVP×2, Co-founder CTO) | Harshit: IIT KGP, Digital Tech Architect, MS Copilot team | Nilesh: 17yr (VP, Solutions Architect, Module Lead, SE)",
    expYears: 20,
    founderSignals: [
      "Yogendra: 9,285 LinkedIn followers (HIGHEST in pool)",
      "Yogendra: 20yr career, signed Pfizer/GSK/HUL",
      "Yogendra: Global Head of Data Distribution (2021-2025)",
      "Harshit: IIT Kharagpur, Microsoft Copilot team experience",
      "Nilesh: VP-level, 17yr engineering career",
      "Blog at blog.colrows.com — actively publishing",
      "Combined: 50+ years experience across 3 founders"
    ],
    website: "blog.colrows.com", hasVideo: true,
    videoSummary: "Professional enterprise pitch. 'Two decades running data platforms at BNRML and MSI.' Mentions Microsoft Copilot team. Well-structured.",
    mentorMatch: "Enterprise SaaS, data infra, B2B sales",
    risk: "Too senior for weekend sprint? Complex enterprise product.",
    scores: { founderCredibility: 10, techDepth: 9, industryFit: 8, commitment: 9, epochReadiness: 6 },
    totalScore: 42,
    phone: "+91 9406646575 / +91 78753 84888 / +917755991051", email: "harshit@colrows.com"
  },
  {
    name: "Rahul Dange", rank: 14, tier: "A", tierLabel: "Interview",
    city: "Pune/Thane", age: "~32-35", track: "STAGE 0", applyType: "solo", canCommit: "yes_all",
    vertical: "HealthTech / Pharma / Local Commerce",
    building: "Mediz — real-time medicine marketplace connecting customers ↔ pharmacies",
    headline: "Lead Mobile Engineer - Flutter | Android",
    linkedin: "linkedin.com/in/rahuldange09", liFollowers: 962, liConnections: 962,
    github: null, ghRepos: 0, ghOriginal: 0, ghStars: 0, ghLanguages: "",
    education: "VES Institute of Technology — Computer Engineering",
    experience: "Lead Mobile Eng @ Dezerv (2022-present) + Lead Mobile Core Team [Sarvatra] (2019-2022) + Android Intern (2017)",
    expYears: 8,
    founderSignals: [
      "VIDEO CONFIRMED: '20+ years software dev, senior technical architect, UPI SDKs for Tata Neu'",
      "Lead Mobile Engineer at Dezerv (2022-present)",
      "Core Team at Sarvatra (2019-2022) — built CardSafe (verified via India Copyright Office)",
      "Copyright registered: 'Sarvatra Cardsafe Mobile Application (Flutter)' Sep 2025",
      "Built UPI apps, AEPS apps for cooperative banks"
    ],
    website: null, hasVideo: true,
    videoSummary: "CONFIRMS on camera: '20+ years software development, led team as senior technical architect, built mobile banking apps and UPI SDKs for Tata Neu.' Mediz pitch is clear and specific.",
    mentorMatch: "HealthTech, marketplace, mobile-first India, fintech",
    risk: "Note: LinkedIn shows ~8yr career, video says 20+. May include pre-LinkedIn experience.",
    scores: { founderCredibility: 8, techDepth: 9, industryFit: 9, commitment: 10, epochReadiness: 8 },
    totalScore: 44,
    phone: "+919860488395", email: "rahul.dange@gmail.com"
  },
  {
    name: "Dhruv Gadiya", rank: 15, tier: "A", tierLabel: "Interview",
    city: "Pune", age: "19", track: "STAGE 1", applyType: "team", canCommit: "yes_all",
    vertical: "Web3 / Payments / API Infrastructure",
    building: "PayGate — x402 payment infra for APIs (USDC from AI agents + humans)",
    headline: "SDE @Oasiz | Founding Engineer @RiveraLabs | Full Stack Blockchain Developer | 4x Hackathon Winner",
    linkedin: "linkedin.com/in/dhruvieiei", liFollowers: 628, liConnections: 618,
    github: null, ghRepos: 0, ghOriginal: 0, ghStars: 0, ghLanguages: "",
    education: "Ajeenkya DY Patil University — BTech",
    experience: "Game Dev @ Oasiz SF (2025-present) + Founding Eng @ Rivera Labs (2026-present) + Freelancer (2024-present)",
    expYears: 3,
    founderSignals: [
      "Only 19 years old with serious pedigree",
      "VIDEO: 'Started coding at 12, shipped 100+ projects, 20+ hackathons, won 5'",
      "4x Hackathon Winner (headline) — including highest bounty ETH Mumbai",
      "Shipped Oasiz iOS app (1000+ users per video, 500+ per application)",
      "SDE at Oasiz (San Francisco, remote)",
      "Founding Engineer at Rivera Labs",
      "Skills: JS, TS, C++, React, Next, Node, Postgres, Docker, Redis, AWS, Rust, Solidity, React Native"
    ],
    website: "dhruv.0xdevs.in", hasVideo: true,
    videoSummary: "'Started coding when I was 12. Shipped 100+ projects, 20+ hackathons, winning 5. Contributed to GSoC, Summer of Bitcoin.' Oasiz app has 1000+ users. Strong energy.",
    mentorMatch: "Web3, payments, API monetization, developer tools",
    risk: "Web3 niche may not hit revenue in 4 weeks. But builder pedigree at 19 is remarkable.",
    scores: { founderCredibility: 8, techDepth: 9, industryFit: 7, commitment: 10, epochReadiness: 7 },
    totalScore: 41,
    phone: "+918908901008", email: "dhruvxop19@gmail.com"
  },
  {
    name: "Nilesh Varma", rank: 16, tier: "A", tierLabel: "Interview",
    city: "Pune", age: "~42-45", track: "STAGE 1", applyType: "solo", canCommit: "yes_all",
    vertical: "Events Marketplace + Payments/FinTech",
    building: "Marketplace for Event Vendors",
    headline: "CoFounder & Director at BNT SOFT | Payments | Fintech",
    linkedin: "linkedin.com/in/nileshvarma", liFollowers: 1342, liConnections: 804,
    github: null, ghRepos: 0, ghOriginal: 0, ghStars: 0, ghLanguages: "",
    education: "Savitribai Phule Pune University — BE",
    experience: "CoFounder BNT SOFT (present) + Project Lead ISTS Worldwide (2006-2011) + System Analyst (2004-2006)",
    expYears: 21,
    founderSignals: [
      "Co-Founder & Director at BNT SOFT — payments company",
      "21 years global financial services (US, India, Middle East)",
      "Was hiring 50+ engineers (LinkedIn post)",
      "Crunchbase profile exists",
      "LAZIEST application in pool — but ELITE background"
    ],
    website: null, hasVideo: false,
    videoSummary: null,
    mentorMatch: "FinTech, payments, marketplace, enterprise",
    risk: "Low-effort application. Interview to gauge actual commitment.",
    scores: { founderCredibility: 9, techDepth: 7, industryFit: 7, commitment: 6, epochReadiness: 5 },
    totalScore: 34,
    phone: "9890451667", email: "nilesh@bnt-soft.com"
  },
  {
    name: "Prashant Patil (BAAS)", rank: 17, tier: "A", tierLabel: "Interview",
    city: "Pune", age: "~24-26", track: "STAGE 0", applyType: "team", canCommit: "unsure",
    vertical: "Aerospace / Deep Tech",
    building: "Reusable sub-orbital & orbital launch vehicles",
    headline: "Tech | Finance | Business",
    linkedin: "linkedin.com/in/prashant-patil-b4126a13b", liFollowers: 258, liConnections: 256,
    github: null, ghRepos: 0, ghOriginal: 0, ghStars: 0, ghLanguages: "",
    education: "Savitribai Phule Pune University — BE",
    experience: "Co-founder BAAS Technologies (2024-present) + Frontend Dev (2023-24) + Co-Founder earlier venture (2022-24) + Web Dev Intern (2023)",
    expYears: 3,
    founderSignals: [
      "BAAS Technologies — incubated at IIT Bombay-SINE",
      "Also incubated at ARAI",
      "F6S profile confirms real aerospace startup",
      "Team of 5+"
    ],
    website: "baas.co.in", hasVideo: false,
    videoSummary: null,
    mentorMatch: "Deep tech, aerospace, hardware, fundraising",
    risk: "commitment = 'unsure'. Aerospace ≠ 4-weekend revenue.",
    scores: { founderCredibility: 7, techDepth: 6, industryFit: 5, commitment: 4, epochReadiness: 3 },
    totalScore: 25,
    phone: "+919665237210", email: "prashant@baas.co.in"
  },
  {
    name: "Almas Sayyed", rank: 18, tier: "B", tierLabel: "Conditional",
    city: "Pimpri-Chinchwad", age: "~35-38", track: "STAGE 0", applyType: "solo", canCommit: "yes_all",
    vertical: "Community / Web3 / Marketing",
    building: "Ecosystem building for Pune (T-Hub equivalent)",
    headline: "Founder PuneDAO | Product Marketing Consultant | AI + Web3 | Ex-Infosys",
    linkedin: "linkedin.com/in/almassayyed", liFollowers: 6398, liConnections: 6047,
    github: null, ghRepos: 0, ghOriginal: 0, ghStars: 0, ghLanguages: "",
    education: "MSc Computer Science",
    experience: "zkMonk Marketing Mgr (2025) + Zugrama (2024-25) + Foundership (2023-25) + Phoenix Guild (2022) + Digital Marketing (2020-21) + Marketing Mgr (2016) + Mondelez/Infosys Testing (2014-15) + Nike Process Monitoring (2012-13)",
    expYears: 13,
    founderSignals: [
      "Founder PuneDAO — 2000+ members, 100+ events in 4 years",
      "Ex-Infosys (Testing Analyst for Mondelez)",
      "Process Monitoring Analyst at Nike",
      "6,398 LinkedIn followers (3rd highest!)",
      "14+ years professional experience",
      "10 LinkedIn positions",
      "MSc Computer Science",
      "SheFi Cohort 12"
    ],
    website: "almas.pop.site", hasVideo: true,
    videoSummary: "Long, detailed. Masters CS, Infosys, solo marketing agency post-COVID. PuneDAO from 0 to 2000+. 'How T Hub is to Hyderabad, I want that in Pune.'",
    mentorMatch: "Community, Web3, marketing, ecosystem development",
    risk: "Not building a traditional product. Ecosystem connector.",
    scores: { founderCredibility: 8, techDepth: 4, industryFit: 6, commitment: 10, epochReadiness: 5 },
    totalScore: 33,
    phone: "+918263839962", email: "almas.sayyed@gmail.com"
  },
  {
    name: "Tushar Kanavalli", rank: 19, tier: "B", tierLabel: "Conditional",
    city: "Pune", age: "~28-32", track: "STAGE 1", applyType: "solo", canCommit: "yes_all",
    vertical: "Consumer Hardware / Kids Tech / EdTech",
    building: "AI Stickerbox — voice-activated toy → physical stickers",
    headline: "User Researcher & Design Strategist | ex-Meesho | Prototyping",
    linkedin: "linkedin.com/in/tushar-kanavalli-bb5589192", liFollowers: 410, liConnections: 406,
    github: null, ghRepos: 0, ghOriginal: 0, ghStars: 0, ghLanguages: "",
    education: "Institute For Design Led Entrepreneurship (IfDE)",
    experience: "UX Research @ GarageWorks (2023-24) + Design Researcher @ Meesho (2022) + Co-Founder (2021) + Jr UX Researcher (2020-21) + Design Researcher (2020) + Founder (2017-19)",
    expYears: 8,
    founderSignals: [
      "Ex-Meesho (unicorn) — Design Researcher",
      "4th startup attempt — honest about 3 prior failures",
      "7+ years in design/product research",
      "Working prototype exists (video + drive link)",
      "CS graduate"
    ],
    website: null, hasVideo: true,
    videoSummary: "Honest about past failures: 'tried healthy food, sustainable logistics, agriculture — not successful.' AI Stickerbox is 4th attempt. Looking to go from prototype to production.",
    mentorMatch: "Consumer hardware, EdTech, product design, manufacturing",
    risk: "Non-technical founder. Needs tech co-founder.",
    scores: { founderCredibility: 7, techDepth: 4, industryFit: 7, commitment: 10, epochReadiness: 6 },
    totalScore: 34,
    phone: "7411547279", email: "tusharkanavalli@gmail.com"
  },
  {
    name: "Muhammed Umar Shaikh", rank: 20, tier: "B", tierLabel: "Conditional",
    city: "Pune", age: "~22-24", track: "STAGE 1", applyType: "team", canCommit: "yes_all",
    vertical: "AutoTech / Dealer Management SaaS",
    building: "MotorIQ — vehicle management for used car dealerships",
    headline: "Software Engineer (SDE) | MERN Stack | Java Backend | AI/LLM Systems",
    linkedin: "linkedin.com/in/muhammed-umar-shaikh-", liFollowers: 641, liConnections: 636,
    github: null, ghRepos: 0, ghOriginal: 0, ghStars: 0, ghLanguages: "",
    education: "Trinity College of Engineering — BE",
    experience: "SE Intern @ Jazar Tech (2024-25) + Full Stack Intern (2024) + Cloud Computing Intern (2024) + Web Dev Intern (2023)",
    expYears: 2,
    founderSignals: [
      "Live product: motor-iq-two.vercel.app",
      "18% GST Margin Engine (compliance-critical)",
      "AI via Gemini, RTO-professional invoices",
      "Team of 2 (both tech leads)"
    ],
    website: "motor-iq-two.vercel.app", hasVideo: true,
    videoSummary: "⚠️ NO SPEECH in video — silent screen recording.",
    mentorMatch: "Automotive, B2B SaaS, compliance tech",
    risk: "Silent video = communication concern. Niche market. Two tech leads, no business person.",
    scores: { founderCredibility: 6, techDepth: 7, industryFit: 7, commitment: 10, epochReadiness: 6 },
    totalScore: 36,
    phone: "+919604646511", email: "muhammedumarshaikh7@gmail.com"
  },
  {
    name: "Sahil + Bharat (Markubees)", rank: 21, tier: "B", tierLabel: "Conditional",
    city: "Haryana / Pune", age: "~22-24", track: "STAGE 1", applyType: "team", canCommit: "remote/yes_all",
    vertical: "Marketplace / Expert Network",
    building: "Platform connecting startups with specialized experts for 1-on-1 calls",
    headline: "Co-founder @ Markubees | Building a platform for direct conversations with experts",
    linkedin: "linkedin.com/in/sahil-9ab669306", liFollowers: 34, liConnections: 34,
    github: null, ghRepos: 0, ghOriginal: 0, ghStars: 0, ghLanguages: "",
    education: "Deen Dayal Upadhyaya College — BSc",
    experience: "Co-founder Markubees Technologies Pvt Ltd (2026-present)",
    expYears: 1,
    founderSignals: [
      "Registered company: Markubees Technologies Private Limited",
      "Fully functional platform with video calling + payments",
      "markubees.com is live"
    ],
    website: "markubees.com", hasVideo: true,
    videoSummary: "Joint video, both speak. Clear problem/solution. Professional but somewhat generic.",
    mentorMatch: "Marketplace dynamics, expert networks",
    risk: "Sahil wants REMOTE. Only Bharat in person. 34 LinkedIn followers = very early.",
    scores: { founderCredibility: 5, techDepth: 6, industryFit: 6, commitment: 6, epochReadiness: 5 },
    totalScore: 28,
    phone: "+919728062717", email: "sahil@markubees.com"
  },
  {
    name: "Suyash Dhumal + Abhay", rank: 22, tier: "B", tierLabel: "Conditional",
    city: "Pune", age: "~21-23", track: "STAGE 1", applyType: "team", canCommit: "yes_all",
    vertical: "EdTech / Lab Management",
    building: "ICYWALL/LockStep — real-time distributed lab management for 200+ computers",
    headline: "Not found on LinkedIn",
    linkedin: null, liFollowers: 0, liConnections: 0,
    github: null, ghRepos: 0, ghOriginal: 0, ghStars: 0, ghLanguages: "",
    education: "Unknown",
    experience: "Student builders",
    expYears: 0,
    founderSignals: [
      "Technically impressive: 200+ computers, sub-second latency",
      "WebSocket communication, SFU-based broadcasting",
      "Multi-instance scalable architecture"
    ],
    website: null, hasVideo: true,
    videoSummary: "Well-structured technical pitch. 'Not just monitoring labs, modernizing how they are managed.' Sounds more product demo than founder pitch.",
    mentorMatch: "EdTech, enterprise software",
    risk: "Academic project feel. Revenue path unclear in 4 weekends.",
    scores: { founderCredibility: 4, techDepth: 7, industryFit: 5, commitment: 10, epochReadiness: 4 },
    totalScore: 30,
    phone: "+91 93569 85557", email: "suyash00016@gmail.com"
  },
  {
    name: "Ganesh Jadhawar", rank: 23, tier: "C", tierLabel: "Pass",
    city: "Pune", age: "~35-38", track: "STAGE 0", applyType: "solo", canCommit: "unsure",
    vertical: "Digital Marketing",
    building: "Digital marketing service/platform for businesses",
    headline: "Program Manager | CSR & Skill Development | Corporate Trainer | 12+ Years",
    linkedin: "linkedin.com/in/ganesh-jadhawar-591809214", liFollowers: 596, liConnections: 596,
    github: null, ghRepos: 0, ghOriginal: 0, ghStars: 0, ghLanguages: "",
    education: "SPPU — Master's degree",
    experience: "12+ years at MITCON Consultancy",
    expYears: 12,
    founderSignals: ["12 years at MITCON", "Corporate Trainer", "AI Adoption Expert (25+ tools)"],
    website: null, hasVideo: false, videoSummary: null,
    mentorMatch: "Digital marketing, training", risk: "commitment = 'unsure'. Generic application.",
    scores: { founderCredibility: 5, techDepth: 3, industryFit: 5, commitment: 3, epochReadiness: 3 },
    totalScore: 19,
    phone: "9021446252", email: "ganesmail7@gmail.com"
  },
  {
    name: "Aviral Sangal", rank: 24, tier: "C", tierLabel: "Pass",
    city: "Pune", age: "~20-21", track: "STAGE 0", applyType: "solo", canCommit: "yes_all",
    vertical: "HealthTech / Wellness",
    building: "FemSafe (women's safety) + VrikshaAI (health/wellness AI)",
    headline: "Attended Symbiosis Skills & Professional University",
    linkedin: "linkedin.com/in/aviral-sangal-9b40a0322", liFollowers: 1355, liConnections: 1357,
    github: null, ghRepos: 0, ghOriginal: 0, ghStars: 0, ghLanguages: "",
    education: "Symbiosis Skills University — BTech AI",
    experience: "Student", expYears: 0,
    founderSignals: ["BTech AI student", "1,355 followers for a student is decent"],
    website: null, hasVideo: false, videoSummary: null,
    mentorMatch: "Wellness tech", risk: "Generic descriptions, no traction.",
    scores: { founderCredibility: 3, techDepth: 3, industryFit: 4, commitment: 10, epochReadiness: 3 },
    totalScore: 23,
    phone: "9322693940", email: "aviralsangal18@gmail.com"
  },
  {
    name: "Neel Rawal + Omkar", rank: 25, tier: "C", tierLabel: "Pass",
    city: "Pune", age: "~21-22", track: "STAGE 1", applyType: "team", canCommit: "yes_all",
    vertical: "EdTech / AI Learning",
    building: "Mentora AI — hands-on AI tools learning platform",
    headline: "Java Developer | AI/ML | Startup Mindset | Founder in the Making",
    linkedin: "linkedin.com/in/neel-rawal-711a8b294", liFollowers: 1231, liConnections: 1220,
    github: null, ghRepos: 0, ghOriginal: 0, ghStars: 0, ghLanguages: "",
    education: "Smt. Kashibai Navale College — BE",
    experience: "IIC E-Cell + AI/ML Team + IoT Intern",
    expYears: 1,
    founderSignals: ["Platform live (the-mentora-ai-frontend.vercel.app)", "Claims 500+ active learners"],
    website: "the-mentora-ai-frontend.vercel.app", hasVideo: false, videoSummary: null,
    mentorMatch: "EdTech", risk: "Thin application. 'Right connections and mentorship' as motivation.",
    scores: { founderCredibility: 4, techDepth: 5, industryFit: 5, commitment: 10, epochReadiness: 4 },
    totalScore: 28,
    phone: "9309203642", email: "neelrawal07@gmail.com"
  },
  {
    name: "Parikshit Gavhane", rank: 26, tier: "C", tierLabel: "Pass",
    city: "Pune", age: "~23-24", track: "STAGE 0", applyType: "solo", canCommit: "yes_all",
    vertical: "EdTech / Statistics",
    building: "StatSage — statistics learning platform from first principles",
    headline: "Project Associate - PKC | GIPE'25",
    linkedin: "linkedin.com/in/parikshit-gavhane-31512425b", liFollowers: 437, liConnections: 439,
    github: null, ghRepos: 0, ghOriginal: 0, ghStars: 0, ghLanguages: "",
    education: "Gokhale Institute of Politics & Economics — BSc Economics",
    experience: "Project Associate @ Pune Knowledge Cluster + Research Intern + District Fellow",
    expYears: 2,
    founderSignals: ["StatSage is live (Netlify)", "Economics background, not CS", "PKC = institutional backing"],
    website: "elaborate-cendol-9f2f98.netlify.app", hasVideo: false, videoSummary: null,
    mentorMatch: "EdTech", risk: "Needs Epoch to learn AI, not to build revenue.",
    scores: { founderCredibility: 4, techDepth: 4, industryFit: 5, commitment: 10, epochReadiness: 4 },
    totalScore: 27,
    phone: "7745055120", email: "parikshitgavhane7@gmail.com"
  },
  {
    name: "Neel Pote", rank: 27, tier: "C", tierLabel: "Pass",
    city: "Pune", age: "~21-22", track: "STAGE 0", applyType: "solo", canCommit: "yes_all",
    vertical: "Web3 / DAO",
    building: "Decentralized Y Combinator",
    headline: "(no headline)",
    linkedin: "linkedin.com/in/neel-pote-b09813314", liFollowers: 168, liConnections: 169,
    github: "neelpote", ghRepos: 10, ghOriginal: 10, ghStars: 2, ghLanguages: "TypeScript(4), JS(2), Move(1), Solidity(1)",
    education: "SPPU — Bachelor's",
    experience: "Student + hackathon participant",
    expYears: 0,
    founderSignals: ["10 GitHub repos", "deco-combinator on Stellar Soroban", "Web3 hackathon projects"],
    website: null, hasVideo: false, videoSummary: null,
    mentorMatch: "Web3", risk: "One-liner application. No substance.",
    scores: { founderCredibility: 3, techDepth: 5, industryFit: 4, commitment: 10, epochReadiness: 3 },
    totalScore: 25,
    phone: "9356571969", email: "neelpote96@gmail.com"
  },
  {
    name: "Jurispliot Team (3)", rank: 28, tier: "C", tierLabel: "Pass",
    city: "Pune", age: "~21-22", track: "STAGE 0", applyType: "team", canCommit: "yes_all",
    vertical: "LegalTech",
    building: "Jurispliot — AI-powered legal platform",
    headline: "Various student headlines",
    linkedin: "multiple", liFollowers: 213, liConnections: 207,
    github: null, ghRepos: 0, ghOriginal: 0, ghStars: 0, ghLanguages: "",
    education: "PES Modern College — BTech",
    experience: "Students",
    expYears: 0,
    founderSignals: ["3 duplicate applications", "Copy-pasted answers", "Harshada applied twice"],
    website: null, hasVideo: false, videoSummary: null,
    mentorMatch: "LegalTech", risk: "No product. Duplicate apps. Team coordination already weak.",
    scores: { founderCredibility: 2, techDepth: 2, industryFit: 4, commitment: 10, epochReadiness: 2 },
    totalScore: 20,
    phone: "9921542338", email: "harshadayele19@gmail.com"
  },
  {
    name: "Aditya Jare", rank: 29, tier: "C", tierLabel: "Pass",
    city: "Pune", age: "~20-21", track: "STAGE 1", applyType: "solo", canCommit: "yes_all",
    vertical: "Communication / Chat App",
    building: "Chat app with real-time translation, E2E encryption",
    headline: "Not found on LinkedIn",
    linkedin: null, liFollowers: 0, liConnections: 0,
    github: "AdityaJare", ghRepos: 3, ghOriginal: 3, ghStars: 0, ghLanguages: "Jupyter, Python, HTML",
    education: "Unknown",
    experience: "None visible",
    expYears: 0,
    founderSignals: ["3 GitHub repos, 0 followers", "No differentiation"],
    website: null, hasVideo: false, videoSummary: null,
    mentorMatch: "N/A", risk: "'Self-made billionaire' aspiration without substance.",
    scores: { founderCredibility: 1, techDepth: 2, industryFit: 3, commitment: 10, epochReadiness: 2 },
    totalScore: 18,
    phone: "9579635665", email: "adityajare2004@gmail.com"
  },
  {
    name: "Aswin D", rank: 30, tier: "C", tierLabel: "Pass",
    city: "Salem", age: "~20", track: "STAGE 0", applyType: "solo", canCommit: "yes_all",
    vertical: "E-Commerce",
    building: "Generic e-commerce web app",
    headline: "Not found on LinkedIn",
    linkedin: null, liFollowers: 0, liConnections: 0,
    github: "Aswind12", ghRepos: 1, ghOriginal: 1, ghStars: 0, ghLanguages: "",
    education: "Unknown",
    experience: "Fresher",
    expYears: 0,
    founderSignals: ["1 GitHub repo (portfolio)", "Account created Jan 2025"],
    website: null, hasVideo: false, videoSummary: null,
    mentorMatch: "N/A", risk: "Not Epoch-ready.",
    scores: { founderCredibility: 1, techDepth: 1, industryFit: 2, commitment: 10, epochReadiness: 1 },
    totalScore: 15,
    phone: "+91 88076 28729", email: "aswindn2k4@gmail.com"
  }
];
